version: '3.8'

services:
  mahir-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mahir_user:secure_pass@db:5432/mahir_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mahir_user
      - POSTGRES_PASSWORD=secure_pass
      - POSTGRES_DB=mahir_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
